# 端口
server:
  port: 8006

spring:
  application:
    # 应用名称
    name: node06-boot-jdbc
  datasource:
    # 数据源一：data_one 库
    primary:
      # 2.0开始的版本必须这样配置
      jdbc-url: jdbc:mysql://localhost:3306/data_one
      #url: jdbc:mysql://localhost:3306/data_one
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
    # 数据源二：data_two 库
    secondary:
      # 2.0开始的版本必须这样配置
      jdbc-url: jdbc:mysql://localhost:3306/data_two
      #url: jdbc:mysql://localhost:3306/data_two
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver